const ClubsTypes = {
  GET_CLUBS_START: "GET_CLUBS_START",
  GET_CLUBS_SUCCESS: "GET_CLUBS_SUCCESS",
  GET_CLUBS_FAIL: "GET_CLUBS_FAIL",
  GET_ALL_CLUBS_START: "GET_ALL_CLUBS_START",
  GET_ALL_CLUBS_SUCCESS: "GET_ALL_CLUBS_SUCCESS",
  GET_ALL_CLUBS_FAIL: "GET_ALL_CLUBS_FAIL",
  SET_SELECTED_CLUB: "SET_SELECTED_CLUB",
  RESET_SELECTED_CLUB: "RESET_SELECTED_CLUB",
  CLUBS_HAS_CHANGE: "CLUBS_HAS_CHANGE",
  DELETE_CLUB_CANCEL: "DELETE_CLUB_CANCEL",
  DELETE_CLUB_START: "DELETE_CLUB_START",
  DELETE_CLUB_SUCCESS: "DELETE_CLUB_SUCCESS",
  DELETE_CLUB_FAIL: "DELETE_CLUB_FAIL",
  RESET_DELETE_CLUB_SUCCESS: "RESET_DELETE_CLUB_SUCCESS",
  RESET_DELETE_CLUB_LOADING: "RESET_DELETE_CLUB_LOADING",
  RESET_DELETE_CLUB_ERROR: "RESET_DELETE_CLUB_ERROR",
};

export default ClubsTypes;
