const ClubsTypes = {
  GET_CLUBS_START: "GET_CLUBS_START",
  GET_CLUBS_SUCCESS: "GET_CLUBS_SUCCESS",
  GET_CLUBS_FAIL: "GET_CLUBS_FAIL",
  SET_SELECTED_CLUB: "SET_SELECTED_CLUB",
  RESET_SELECTED_CLUB: "RESET_SELECTED_CLUB",
  CLUBS_HAS_CHANGE: "CLUBS_HAS_CHANGE",
};

export default ClubsTypes;
