const TeamsTypes = {
  GET_TEAMS_START: "GET_TEAMS_START",
  GET_TEAMS_SUCCESS: "GET_TEAMS_SUCCESS",
  GET_TEAMS_FAIL: "GET_TEAMS_FAIL",
  SET_SELECTED_TEAM: "SET_SELECTED_TEAM",
  RESET_SELECTED_TEAM: "RESET_SELECTED_TEAM",
  TEAMS_HAS_CHANGE: "TEAMS_HAS_CHANGE",
};

export default TeamsTypes;
