const CompetitionsActionTypes = {
  GET_COMPETITION_START: "GET_COMPETITION_START",
  GET_COMPETITION_SUCCESS: "GET_COMPETITION_SUCCESS",
  GET_COMPETITION_FAIL: "GET_COMPETITION_FAIL",
  SET_SELECTED_COMPETITION: "SET_SELECTED_COMPETITION",
};

export default CompetitionsActionTypes;
